name: CI Pipeline

# Trigger: When do we run this?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Jobs: The actual work
jobs:
  test:
    # The Machine: GitHub will lend us a Linux server
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download  code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies (FastAPI, Pytest, etc.)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the tests (Same command used locally!)
      - name: Run Tests
        run: |
          python -m pytest